const arrayInterviewQuestions = [
 
  { questionText: "What is an array and why is it used in programming?" },
  { questionText: "How do you declare and initialize an array?" },
  { questionText: "What are the advantages and disadvantages of arrays?" },
  { questionText: "How do you traverse an array?" },
  { questionText: "How do you find the length of an array?" },
  { questionText: "What happens if you access an array index that is out of bounds?" },
  { questionText: "What is the difference between one-dimensional and multi-dimensional arrays?" },
  { questionText: "What is a jagged array?" },
  { questionText: "How do you insert an element at a specific position in an array?" },
  { questionText: "How do you delete an element from a specific position in an array?" },
  { questionText: "How do you reverse an array (conceptually)?" },
  { questionText: "What is the difference between arrays and strings?" },
  { questionText: "How do arrays differ from other data structures like linked lists?" },
  { questionText: "What is the difference between array length and array capacity?" },
  { questionText: "How do you check if an array is sorted?" },

  { questionText: "How are arrays stored in memory?" },
  { questionText: "What is the difference between static and dynamic arrays?" },
  { questionText: "What is the time complexity of accessing an element in an array?" },
  { questionText: "What is the time complexity of inserting an element into an array?" },
  { questionText: "What is the time complexity of deleting an element from an array?" },
  { questionText: "What is the difference between linear search and binary search in arrays?" },
  { questionText: "What are the requirements for binary search to work on an array?" },
  { questionText: "How do you find the maximum element in an array?" },
  { questionText: "How do you find the minimum element in an array?" },
  { questionText: "How do you find the sum and average of elements in an array?" },
  { questionText: "How do you remove duplicates from an array?" },
  { questionText: "How do you merge two arrays?" },
  { questionText: "What is the difference between shallow copy and deep copy of arrays?" },
  { questionText: "What are sparse arrays?" },
  { questionText: "How do you sort an array conceptually?" },
  { questionText: "What are some common sorting algorithms used on arrays?" },
  { questionText: "What is the difference between stable and unstable sorting?" },
  { questionText: "How do you rotate an array?" },
  { questionText: "How do you shift elements in an array?" },
  { questionText: "What is the difference between left shift and right shift operations in arrays?" },

  
  { questionText: "What is a two-dimensional array and where is it used?" },
  { questionText: "How are multi-dimensional arrays represented in memory?" },
  { questionText: "What are some real-world applications of arrays?" },
  { questionText: "What is the difference between arrays and matrices?" },
  { questionText: "How do you find the frequency of elements in an array?" },
  { questionText: "What is the difference between dynamic arrays and linked lists?" },
  { questionText: "How do arrays handle memory allocation?" },
  { questionText: "What is the difference between contiguous and non-contiguous memory allocation?" },
  { questionText: "What is the role of pointers in arrays?" },
  { questionText: "What is the difference between arrays and hash tables?" },
  { questionText: "How can arrays be used to implement stacks and queues?" },
  { questionText: "What is the difference between row-major and column-major order in arrays?" },
  { questionText: "How do you handle array overflow?" },
  { questionText: "How does array indexing work in different programming languages?" },
  { questionText: "What are the limitations of arrays compared to other data structures?" }
];

module.exports = arrayInterviewQuestions;