const queueInterviewQuestions = [
  // Basics (15)
  { questionText: "What is a queue in data structures?" },
  { questionText: "What is the FIFO principle in queues?" },
  { questionText: "What are the basic operations of a queue?" },
  { questionText: "What is the difference between enqueue and dequeue operations?" },
  { questionText: "What is the role of front and rear pointers in a queue?" },
  { questionText: "What happens if you dequeue from an empty queue?" },
  { questionText: "What happens if you enqueue into a full queue?" },
  { questionText: "What are the differences between a stack and a queue?" },
  { questionText: "What are some real-life examples of queues?" },
  { questionText: "What are the advantages and disadvantages of queues?" },
  { questionText: "How do you represent a queue in memory?" },
  { questionText: "What is the difference between linear and circular queues?" },
  { questionText: "What is queue overflow and underflow?" },
  { questionText: "How is a queue different from an array?" },
  { questionText: "What are the applications of queues?" },

  // Intermediate (20)
  { questionText: "How can a queue be implemented using arrays?" },
  { questionText: "How can a queue be implemented using linked lists?" },
  { questionText: "What is the time complexity of enqueue and dequeue operations?" },
  { questionText: "What is a circular queue and why is it used?" },
  { questionText: "What are double-ended queues (deques)?" },
  { questionText: "What is the difference between input-restricted and output-restricted deques?" },
  { questionText: "How does a priority queue differ from a normal queue?" },
  { questionText: "What are some applications of circular queues?" },
  { questionText: "How are queues used in operating systems?" },
  { questionText: "What is the role of queues in CPU scheduling?" },
  { questionText: "What is the difference between simple queue and priority queue?" },
  { questionText: "What is the difference between bounded and unbounded queues?" },
  { questionText: "How do queues handle memory allocation?" },
  { questionText: "What are multiple queues and where are they used?" },
  { questionText: "How do queues help in breadth-first search (BFS) algorithm?" },
  { questionText: "What are some differences between static and dynamic queues?" },
  { questionText: "How do you check if a queue is empty or full?" },
  { questionText: "What is the role of a circular buffer in queues?" },
  { questionText: "What are the limitations of linear queues?" },
  { questionText: "How are queues used in printer job scheduling?" },

  // Advanced (15)
  { questionText: "What is the difference between queue and deque?" },
  { questionText: "What is a double-ended priority queue?" },
  { questionText: "How are priority queues implemented?" },
  { questionText: "What is the difference between min-priority and max-priority queues?" },
  { questionText: "How are queues used in graph algorithms?" },
  { questionText: "What is the difference between hardware queues and software queues?" },
  { questionText: "What is the role of queues in network packet management?" },
  { questionText: "How does a queue help in load balancing?" },
  { questionText: "What is the difference between blocking and non-blocking queues?" },
  { questionText: "What is a concurrent queue?" },
  { questionText: "What is the difference between synchronous and asynchronous queues?" },
  { questionText: "What are monotonic queues and where are they used?" },
  { questionText: "How are queues used in memory management?" },
  { questionText: "What is the role of queues in simulation problems?" },
  { questionText: "What are some limitations of queues compared to other data structures?" }
];

module.exports = queueInterviewQuestions;